### ISSUE TITLE
Feature request: Make it working with HA7NET devices

### ISSUE THREAD

**Issue by Foxi352** [lrybak/addon-repository#1]
I have a [HA7NET](https://www.embeddeddatasystems.com/HA7Net--Ethernet-1-Wire-Host-Adapter_p_22.html) 1-wire to ethernet running for a long time. For now owfs is running on separate server and i want to switch to your addon on the HA VM. Sadly it is not possible to configure the device correctly via config UI.

owfs fully supports the HA7NET device. I get it working by doing a `docker exec -it <container-id> /bin/bash` into your addon's container and editing the` /etc/owfs.conf` file. But on every addon restart it is overwriten.

The needed config line in `/etc/owfs.conf` is:
```
server: ha7net = 192.168.2.242
```

But when i enter `ha7net = 192.168.2.242` in the addon's config UI it generates:
```
server: device = ha7net = 192.168.2.242
```

Would it be possible to maybe the user switch in the config between `device`and `ha7net` of just provide an "advanced" option where one can manually edit the config file ?

**Comment by lrybak** [comment]
Hi, looks it's possible with kind of parameter, I will check that and let you know

**Comment by lrybak** [comment]
Btw, can you repost your issue in the addon dedicated issue page @Foxi352 ? 
https://github.com/lrybak/hassio-owserver/issues
That repo does not contain addon code but only some manifest files

**Comment by Foxi352** [comment]
Moved to https://github.com/lrybak/hassio-owserver/issues/13#issue-1749448598 as requested
